apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ferriskey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: ghcr.io/ferriskey/charts
      chart: ferriskey
      targetRevision: 0.3.0
      helm:
        valueFiles:
          - $values/apps/ferriskey/values.yaml
    - repoURL: https://github.com/nathaelb/k-soul.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/nathaelb/k-soul.git
      targetRevision: HEAD
      path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ferriskey-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
